### ISSUE TITLE
Retain time doesn't work

### ISSUE THREAD

**Issue by giuseppevitali** [WikiBox/snapshot.sh#2]
Hi Man,
First of all thanks for your script. Looks great!

I'm running several tests in pre-production and, unfortunately, the folders older than days specified in your variables (keep_daily, keep_weekly and keep_monthly) haven't been deleted.

I found it working just removing the "+" prior the **$max_age_monthly** value of the **mtime** argument into the **find** command.

Furthermore, I haven't found any sign neither any details into the man page about that.
But, would assume you have good reason why you have used it.

Do you know why?
Thanks

**Comment by WikiBox** [comment]
Hi!
Thanks for your interest in my script. I'm sorry but I can't reproduce what you see. 

Please note that $max_age_monthly combines the ages for max_age_daily and max_age_weekly. So if you use keep_daily=7; keep_weekly=4; keep_monthly=2 then max_age_monthly is 7 + 4 * 7 + 2 * 30 = 95 days
I used this script to create old snapshots to test against:

for ((i = 0 ; i < 120 ; i++ )); do 
    mkdir "age_$i"
    touch -d "$i days ago" "age_$i" 
done

The + used in the find command means "more than". If you remove the + it means "exactly" and a - means "less than". So + makes the find command find snapshots **older** than $max_age_monthly and deletes them.

This is described under operands in the find man page:

+n
    More than n.
n
    Exactly n.
-n
    Less than n.
